### ISSUE TITLE
Suggestion: Retrieve wallpapers tags and store them in a text file

### ISSUE THREAD

**Issue by tokiso** [vladdeSV/wallhaven-dl#1]
The Wallhaven wallpaper tags are in the alt html tag of the image. Maybe it would be possible to extract the data from the html alt tag and store it with the name of the image file in a csv file, or in a separate text files for each wallpaper. It would be nice to have a wallpaper database.

**Comment by vladdeSV** [comment]
Heyo, working on it.

Funny thing is I don't know bash, and I mainly did this to learn some bash. Feel free to make a PR request :+1:, I'm just going to fix some bugs in the code :)

**Comment by vladdeSV** [comment]
@tokiso The extra stuff is now stored in the filename.

Some optimization and bugfixes could be done, however I'm no good at bash.

**Comment by vladdeSV** [comment]
Or would you rather prefer a text file/CSV?

**Comment by tokiso** [comment]
I have tried your new script and it works very well. The option of storing the tags in the file is a good idea, because some image files has cero bytes and this way they are filtered better. I don't know bash, but I made a code to store the tags in a csv text file following yours. This way I have the two options. Thanks for your help.

My code:

    tags=$(
    curl -s "http://alpha.wallhaven.cc/wallpaper/$id" --compressed |
    grep -o -E 'alt="([^"#]+)"' #|	
    )
    if [ -n "$stuff" ] ; then
    curl -s -o "wallhaven-$stuff" $(printf "$downloadTemplate" "$stuff")
    else
    echo -e "\t\033[1mImage #$id is not public, or removed. Brute-forcing, JPG only.\033[0m"
    curl -s -o "wallhaven-$id.jpg" $(printf "$downloadTemplate" "$id.jpg")
    fi
    echo -e "\t\033[1mDownloaded image $id\033[0m"
    echo 'wallhaven-'$id'|'$tags >> wallhaven.txt
    sed -e 's/alt="wallhaven"//g' -i wallhaven.txt
    sed -e 's/ alt="//g' -i wallhaven.txt
    sed -e 's/"//g' -i wallhaven.txt
